#!/usr/bin/env python3
"""
Extract each song's REAL peak envelope → waveforms.js

The player draws these directly. The rule under a song is that song's actual
waveform — loud choruses are tall, the breakdown is thin, the outro tapers.
Nothing about the shape is invented.

One byte per column, 1024 columns per song, base64'd: ~1.4KB per track, so the
whole set ships inline and paints instantly (no fetching, no decoding 5MB of
audio in the browser just to know what a song looks like).

    python3 tools/waveforms.py

Re-run it whenever a master changes or a song is added, then bump the
?v=N on waveforms.js in index.html.
"""
import array
import base64
import os
import subprocess
import sys

COLS  = 1024      # columns per song (1 byte each)
RATE  = 22050     # decode rate — ample for a peak envelope, fast to scan
GAMMA = 0.95      # visual curve
FLOOR = 3         # silence still draws a rule, never a gap

# These are brick-walled modern masters: a raw PEAK envelope sits pinned near
# maximum for the whole song and draws as a featureless sausage. So the shape is
# RMS-led (that tracks the arrangement — verse vs chorus vs breakdown) with some
# peak mixed in for transient jaggedness, then stretched across each song's OWN
# dynamic range so its structure is actually visible.
RMS_MIX = 0.62    # rms vs peak
LO_PCT  = 0.04    # bottom of the stretch
HI_PCT  = 0.985   # top of the stretch

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC  = os.path.join(ROOT, "Music for player 1")

# key (matches the mp3 basename in assets/) → source master
SONGS = {
    "insecure":           "i am/01 Insecure.wav",
    "you-hurt-me":        "i am/02 You Hurt Me.wav",
    "i-miss-you":         "i am/03 I Miss You.wav",
    "memories-of-me":     "i am/04 Memories of Me 2.wav",
    "i-am":               "i am/05 I am.wav",
    "mirror":             "mirror/Clay&Kelsy-Mirror4424_JG_Master_2024-12-17 (1).mp3",
    "three-little-birds": "Three Little birds/Three Little Birds (feat. Elder Sister) - Clay and Kelsy (youtube).mp3",
}


def envelope(path):
    """Peak-per-column envelope, normalised and curved, as base64 bytes."""
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", path,
         "-ac", "1", "-ar", str(RATE), "-f", "s16le", "-"],
        check=True, stdout=subprocess.PIPE).stdout

    pcm = array.array("h")
    pcm.frombytes(raw)
    n = len(pcm)
    if n == 0:
        raise SystemExit("no audio decoded from %s" % path)

    per = max(1, n // COLS)
    peaks, rmss = [], []
    for c in range(COLS):
        s = c * per
        e = n if c == COLS - 1 else s + per
        chunk = pcm[s:e]
        if not chunk:
            peaks.append(0.0)
            rmss.append(0.0)
            continue
        peaks.append(max(max(chunk), -min(chunk)) / 32768.0)
        acc = 0
        for v in chunk:
            acc += v * v
        rmss.append((acc / len(chunk)) ** 0.5 / 32768.0)

    def pct(vals, p):
        srt = sorted(vals)
        return srt[min(len(srt) - 1, int(len(srt) * p))]

    # normalise each measure against its own robust top, then blend
    pref = pct(peaks, HI_PCT) or max(peaks) or 1.0
    rref = pct(rmss, HI_PCT) or max(rmss) or 1.0
    mix = [RMS_MIX * min(1.0, r / rref) + (1 - RMS_MIX) * min(1.0, p / pref)
           for p, r in zip(peaks, rmss)]

    # stretch across this song's own range so its structure is visible
    lo, hi = pct(mix, LO_PCT), pct(mix, HI_PCT)
    span = max(1e-6, hi - lo)

    out = bytearray()
    for m in mix:
        v = min(1.0, max(0.0, (m - lo) / span)) ** GAMMA
        out.append(max(FLOOR, min(255, round(v * 255))))
    return base64.b64encode(bytes(out)).decode(), n / float(RATE)


def main():
    lines = []
    for key, rel in SONGS.items():
        path = os.path.join(SRC, rel)
        if not os.path.exists(path):
            print("  !! missing, skipped: %s" % rel, file=sys.stderr)
            continue
        b64, dur = envelope(path)
        print("  %-20s %6.1fs  %d cols" % (key, dur, COLS))
        lines.append('  "%s":\n    "%s",' % (key, b64))

    js = (
        "/* ============================================================\n"
        "   ck-player — REAL waveforms\n"
        "   GENERATED by tools/waveforms.py — do not hand-edit.\n"
        "   One base64 byte per column (%d), peak-normalised, gamma %s.\n"
        "   Keyed by the track's mp3 basename.\n"
        "   ============================================================ */\n\n"
        "window.WAVEFORMS = {\n%s\n};\n" % (COLS, GAMMA, "\n".join(lines))
    )
    dest = os.path.join(ROOT, "waveforms.js")
    with open(dest, "w") as f:
        f.write(js)
    print("→ %s  (%.1f KB)" % (dest, os.path.getsize(dest) / 1024.0))


if __name__ == "__main__":
    main()
